apiVersion: apps/v1
kind: Deployment
metadata:
  name: paltforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: paltformservice
          image: plolon/platformservice:latest